export const input = [
  {
    signal: [
      "dfgabce",
      "cadfgb",
      "cefa",
      "ca",
      "aecbg",
      "dfcegb",
      "geabd",
      "ecbfg",
      "cab",
      "agcfbe",
    ],
    digits: ["egbfadc", "dbgae", "gcfeb", "abgdfc"],
  },

  {
    signal: [
      "fbcag",
      "eg",
      "dbge",
      "gcbfe",
      "acdgfe",
      "gec",
      "fdcegba",
      "efbdc",
      "fbedgc",
      "efabdc",
    ],
    digits: ["ge", "fagbc", "dfebc", "eg"],
  },

  {
    signal: [
      "da",
      "gdbcea",
      "gdcfbe",
      "acgbd",
      "dbfcgea",
      "ebad",
      "aecdfg",
      "afcbg",
      "adc",
      "ecdbg",
    ],
    digits: ["afcegd", "dacebg", "ad", "cdbafeg"],
  },

  {
    signal: [
      "gafeb",
      "ag",
      "acfbed",
      "ega",
      "ebadfg",
      "bfcge",
      "dgfa",
      "begcda",
      "edfba",
      "cfgedba",
    ],
    digits: ["ag", "dafg", "dfcbgea", "feacdb"],
  },

  {
    signal: [
      "cefdag",
      "gcea",
      "fag",
      "defca",
      "gbdaef",
      "afcdg",
      "dcbgf",
      "ga",
      "adfecbg",
      "fcbdea",
    ],
    digits: ["geac", "cfedba", "cgea", "fadecg"],
  },

  {
    signal: [
      "fcgaed",
      "abdecgf",
      "cfaed",
      "ceb",
      "febacd",
      "dbecf",
      "bc",
      "cbfa",
      "gecbad",
      "fbdeg",
    ],
    digits: ["facde", "cfgade", "acdefb", "cbe"],
  },

  {
    signal: [
      "bcgae",
      "cfedba",
      "efcbadg",
      "dafbc",
      "dfbe",
      "fcgbad",
      "ef",
      "aefgcd",
      "acfbe",
      "fea",
    ],
    digits: ["abfcd", "cafbd", "fbde", "dcgbaf"],
  },

  {
    signal: [
      "geabdc",
      "fedga",
      "cafdbg",
      "cd",
      "aefcbg",
      "adcge",
      "dac",
      "bdegafc",
      "cegab",
      "dceb",
    ],
    digits: ["dcfgba", "cad", "cad", "deabcg"],
  },

  {
    signal: [
      "gdecab",
      "fde",
      "aecf",
      "adbgfe",
      "egdcaf",
      "dgaebcf",
      "decfg",
      "bcfdg",
      "ef",
      "ceadg",
    ],
    digits: ["cefdabg", "fcea", "efac", "edf"],
  },

  {
    signal: [
      "cbgaf",
      "edfa",
      "bfgecd",
      "fcdbae",
      "debca",
      "dfb",
      "bcdaf",
      "bdcaeg",
      "fecgadb",
      "fd",
    ],
    digits: ["cafdgeb", "gabcf", "df", "afdebc"],
  },

  {
    signal: [
      "fdebgc",
      "egdfb",
      "bfcdg",
      "cfedgab",
      "fdeagb",
      "egcb",
      "fcb",
      "cfdeba",
      "cb",
      "fagcd",
    ],
    digits: ["gebfd", "afdbgec", "bc", "gdcafbe"],
  },

  {
    signal: [
      "cb",
      "gcdefa",
      "cdb",
      "bacg",
      "eabfd",
      "ebdac",
      "gdabec",
      "gcbefd",
      "bgdecaf",
      "caedg",
    ],
    digits: ["cgdeab", "ebfdgca", "edgbca", "cbefadg"],
  },

  {
    signal: [
      "efbc",
      "aecgbd",
      "ebgdfa",
      "ecbag",
      "afb",
      "cfgeadb",
      "bf",
      "cadgf",
      "bgfca",
      "egcabf",
    ],
    digits: ["bf", "agdbce", "fab", "bfcdeag"],
  },

  {
    signal: [
      "cedafg",
      "aecdbg",
      "fcd",
      "cgeda",
      "cdfag",
      "efcg",
      "agfdb",
      "defcab",
      "fagcebd",
      "cf",
    ],
    digits: ["adgcfe", "daecg", "abcged", "fgedbca"],
  },

  {
    signal: [
      "bcgaed",
      "cfdgea",
      "caebd",
      "gdebc",
      "bega",
      "fbecadg",
      "ge",
      "fcdaeb",
      "gde",
      "gfbdc",
    ],
    digits: ["gabe", "eg", "cadebf", "ecgadf"],
  },

  {
    signal: [
      "aefc",
      "abefg",
      "acfbge",
      "agedbf",
      "dbgce",
      "cab",
      "abgdfc",
      "ecbga",
      "ac",
      "bfdceag",
    ],
    digits: ["beafgd", "ca", "ac", "ac"],
  },

  {
    signal: [
      "afbde",
      "fedag",
      "becda",
      "dacegf",
      "baf",
      "gacdbfe",
      "fcabdg",
      "fgeb",
      "fgdabe",
      "fb",
    ],
    digits: ["fb", "afbdge", "bcdea", "fedacbg"],
  },

  {
    signal: [
      "bfd",
      "cdgbfa",
      "dgefca",
      "fabdeg",
      "cgebdfa",
      "cabd",
      "gfcda",
      "cbgef",
      "db",
      "dgfcb",
    ],
    digits: ["bd", "badegcf", "acdb", "adegcf"],
  },

  {
    signal: [
      "ef",
      "cfbgd",
      "cdbfe",
      "bef",
      "ceadb",
      "bfcgead",
      "aedf",
      "edbagc",
      "abgcef",
      "aecbdf",
    ],
    digits: ["bcfegad", "bef", "bef", "fe"],
  },

  {
    signal: [
      "cbagef",
      "beadgc",
      "fae",
      "deacb",
      "fcagd",
      "cgdebfa",
      "dfeb",
      "bdecaf",
      "fe",
      "fcdae",
    ],
    digits: ["dfaceb", "efdb", "beafcg", "bdef"],
  },

  {
    signal: [
      "gdfeacb",
      "bca",
      "gfeacb",
      "gfeca",
      "egcb",
      "bc",
      "dgeacf",
      "fabgd",
      "fbcdae",
      "gcbfa",
    ],
    digits: ["bfdeca", "bca", "adbgf", "abdgf"],
  },

  {
    signal: [
      "faedbc",
      "egcaf",
      "bdgaf",
      "agdebcf",
      "fagcb",
      "cab",
      "bcdgaf",
      "dbgc",
      "fbgead",
      "cb",
    ],
    digits: ["bdgafc", "cb", "dgbfa", "bgcd"],
  },

  {
    signal: [
      "dfabc",
      "bgacde",
      "ad",
      "dab",
      "edfa",
      "bdfec",
      "dbgefca",
      "facgb",
      "eacfbd",
      "fcgdeb",
    ],
    digits: ["ecdbfag", "bedfc", "ebfcad", "bfcdge"],
  },

  {
    signal: [
      "dfegbc",
      "cfagb",
      "ba",
      "gefbc",
      "abec",
      "bfcdega",
      "bfa",
      "egadbf",
      "fgbcea",
      "fgcda",
    ],
    digits: ["eafbdg", "ebfgc", "fgbdcea", "ba"],
  },

  {
    signal: [
      "fgdebca",
      "dgbcea",
      "adbce",
      "cfaedb",
      "acebf",
      "ef",
      "efc",
      "cfabg",
      "edgafc",
      "fedb",
    ],
    digits: ["fdeb", "fce", "gcfab", "bafgc"],
  },

  {
    signal: [
      "cfdg",
      "daefgcb",
      "caedgb",
      "aefbc",
      "cbdag",
      "fg",
      "fdbgac",
      "fbg",
      "beagdf",
      "fbcga",
    ],
    digits: ["dgfc", "fecgabd", "fgcd", "gbf"],
  },

  {
    signal: [
      "cbadef",
      "abgdef",
      "cfea",
      "ac",
      "gedbc",
      "dcbafg",
      "dca",
      "fdbecag",
      "dceab",
      "deafb",
    ],
    digits: ["eafc", "ebfdga", "cefa", "abcde"],
  },

  {
    signal: [
      "fcbged",
      "ebdca",
      "bde",
      "ceagb",
      "abcdfeg",
      "bd",
      "cdaef",
      "cgabed",
      "ecgfab",
      "bgda",
    ],
    digits: ["baecd", "dgbcea", "ecafd", "dbag"],
  },

  {
    signal: [
      "bfeag",
      "cdabf",
      "dbeacg",
      "dgbcefa",
      "eda",
      "fdabge",
      "bafde",
      "ed",
      "egfd",
      "ebcafg",
    ],
    digits: ["ebfcadg", "defg", "fadbe", "cfbgea"],
  },

  {
    signal: [
      "bfd",
      "dgbec",
      "gfcadb",
      "ecdf",
      "aefbg",
      "cfbgead",
      "fd",
      "gcbdfe",
      "debgf",
      "gcdeab",
    ],
    digits: ["ecdbga", "aebgf", "abcfgde", "fd"],
  },

  {
    signal: [
      "ecgfda",
      "bcafe",
      "dgbefca",
      "dagcb",
      "dfc",
      "acdfb",
      "cdabfe",
      "cebfag",
      "fbde",
      "fd",
    ],
    digits: ["bgdefac", "cfd", "febgac", "df"],
  },

  {
    signal: [
      "dcafb",
      "dgafcb",
      "dbeacf",
      "bdga",
      "degbcfa",
      "cgbaf",
      "ga",
      "fga",
      "efdgca",
      "cegfb",
    ],
    digits: ["ag", "beagdfc", "abcfg", "gcdeaf"],
  },

  {
    signal: [
      "cgbfd",
      "fegcba",
      "ecgfb",
      "cbe",
      "dafebg",
      "bdface",
      "gace",
      "ec",
      "fcgdeab",
      "eagfb",
    ],
    digits: ["gcdfb", "acge", "ecb", "cebgf"],
  },

  {
    signal: [
      "adbcgf",
      "ef",
      "fged",
      "feb",
      "dabfgce",
      "bdgfc",
      "becfgd",
      "dcabe",
      "febgac",
      "bdfec",
    ],
    digits: ["cgdbf", "fdcgeb", "afcbge", "fbdgc"],
  },

  {
    signal: [
      "cg",
      "dagfc",
      "dfagbc",
      "cgab",
      "dagbf",
      "gbdcfe",
      "dgc",
      "aefgdbc",
      "aecdf",
      "bafegd",
    ],
    digits: ["cg", "gfacbed", "bfgad", "bgacfed"],
  },

  {
    signal: [
      "cadfeg",
      "cfdegba",
      "edagcb",
      "fae",
      "faebc",
      "decfb",
      "fa",
      "aebcg",
      "fgba",
      "egafcb",
    ],
    digits: ["baegc", "fa", "acfbe", "af"],
  },

  {
    signal: [
      "fed",
      "bcdge",
      "fcbae",
      "gbfd",
      "gfabecd",
      "cdaegb",
      "df",
      "egdfac",
      "egcfbd",
      "becdf",
    ],
    digits: ["cadegf", "edcgbf", "fcbde", "dbgf"],
  },

  {
    signal: [
      "fadcg",
      "beafcd",
      "cedbag",
      "edabg",
      "abdfge",
      "bdagf",
      "fba",
      "dgcbaef",
      "fb",
      "fbge",
    ],
    digits: ["deafcgb", "dfcaeb", "geadfb", "ecfgdba"],
  },

  {
    signal: [
      "bec",
      "fbcea",
      "cgbf",
      "bfgcea",
      "cdefa",
      "cgadeb",
      "cb",
      "fdbeag",
      "bdaegcf",
      "fgabe",
    ],
    digits: ["ebfacg", "bgcf", "cb", "bc"],
  },

  {
    signal: [
      "gb",
      "agdbce",
      "efacgd",
      "cgdfbe",
      "agdec",
      "afcdb",
      "ebag",
      "gcb",
      "eadfgcb",
      "bdgac",
    ],
    digits: ["efcbagd", "bedcag", "bgc", "baeg"],
  },

  {
    signal: [
      "fbe",
      "dcbgae",
      "cedgfba",
      "bcgefa",
      "bfdge",
      "bf",
      "dafge",
      "edbgc",
      "fcdb",
      "bcfdeg",
    ],
    digits: ["bdfc", "fdabgce", "ebgfd", "fegbd"],
  },

  {
    signal: [
      "fb",
      "abfdge",
      "fgdca",
      "fedcag",
      "bafcgd",
      "bfg",
      "gdeabfc",
      "fbgac",
      "eagcb",
      "bcdf",
    ],
    digits: ["gacfedb", "fb", "bf", "fcadg"],
  },

  {
    signal: [
      "bg",
      "eadgf",
      "bcdea",
      "gbd",
      "gebda",
      "edgbac",
      "cagb",
      "dfecab",
      "fgcbead",
      "ecfbgd",
    ],
    digits: ["gbedca", "adfebgc", "acgb", "bdg"],
  },

  {
    signal: [
      "adgfce",
      "begafc",
      "gfeac",
      "cde",
      "cgabd",
      "ed",
      "becdfa",
      "gfed",
      "egfbcda",
      "egacd",
    ],
    digits: ["ed", "cgeda", "dfeacb", "dec"],
  },

  {
    signal: [
      "agefcb",
      "gadec",
      "gdbafe",
      "dg",
      "cebafdg",
      "dcfg",
      "ecagf",
      "edg",
      "gdeacf",
      "ceadb",
    ],
    digits: ["dgaefc", "egcadbf", "cdfg", "faecg"],
  },

  {
    signal: [
      "fdec",
      "gcbdaf",
      "bafedc",
      "cf",
      "dbegac",
      "ceabd",
      "gbadecf",
      "fca",
      "gbefa",
      "bacfe",
    ],
    digits: ["fc", "fdce", "acf", "afc"],
  },

  {
    signal: [
      "fdecg",
      "gdefcba",
      "cg",
      "dbcfe",
      "dfbeac",
      "gcfedb",
      "daefg",
      "facdgb",
      "gebc",
      "cfg",
    ],
    digits: ["begafdc", "fcdebag", "dbcgaef", "gfc"],
  },

  {
    signal: [
      "adcgef",
      "agbdfec",
      "dc",
      "ecad",
      "cgeabf",
      "edfbg",
      "bcdgaf",
      "fdgce",
      "ceagf",
      "cdg",
    ],
    digits: ["cdgef", "ecda", "cade", "cd"],
  },

  {
    signal: [
      "abdefc",
      "bdaecfg",
      "dgeacb",
      "fb",
      "gfade",
      "bacde",
      "bdagcf",
      "fdb",
      "becf",
      "adbef",
    ],
    digits: ["fcbadg", "cefabd", "fdb", "edfga"],
  },

  {
    signal: [
      "efcgab",
      "bead",
      "fcdeg",
      "ae",
      "cgdab",
      "dgcbae",
      "aeg",
      "edgca",
      "bcegdaf",
      "gdcfab",
    ],
    digits: ["gdafceb", "ea", "eag", "aeg"],
  },

  {
    signal: [
      "dceafb",
      "befac",
      "fca",
      "cf",
      "fdcb",
      "cadgef",
      "bedaf",
      "ebagc",
      "aedfbg",
      "acgdbef",
    ],
    digits: ["beadfc", "cf", "cfeba", "gbeca"],
  },

  {
    signal: [
      "gce",
      "eacgbd",
      "afcdbe",
      "eg",
      "dfcebga",
      "bedca",
      "gfbca",
      "agfedc",
      "gcaeb",
      "gebd",
    ],
    digits: ["gdbe", "ge", "ge", "gbde"],
  },

  {
    signal: [
      "bcgae",
      "bedgfca",
      "gde",
      "ed",
      "gdaec",
      "gbfcad",
      "cgbdef",
      "gdaecf",
      "edfa",
      "gfadc",
    ],
    digits: ["cdbfeg", "bgdfac", "cfdeag", "adgfbc"],
  },

  {
    signal: [
      "gebca",
      "dbacfeg",
      "dbfeag",
      "bagfe",
      "eadfb",
      "gf",
      "fdge",
      "fbg",
      "dfceba",
      "gafbdc",
    ],
    digits: ["egfd", "fedg", "egafb", "gf"],
  },

  {
    signal: [
      "begfadc",
      "bdcae",
      "dgbca",
      "edbf",
      "acbfeg",
      "fcgead",
      "be",
      "eba",
      "afdce",
      "aedcbf",
    ],
    digits: ["bfedac", "edcab", "eba", "fdbace"],
  },

  {
    signal: [
      "fdbgc",
      "cegabf",
      "ac",
      "dfbage",
      "bgfae",
      "faec",
      "gac",
      "caedbg",
      "bfgedca",
      "bfagc",
    ],
    digits: ["acef", "dfgcb", "face", "gbafed"],
  },

  {
    signal: [
      "cdbfge",
      "bfceg",
      "dgacbe",
      "baegfd",
      "ecb",
      "dfceabg",
      "ebdfg",
      "cb",
      "acfge",
      "bdfc",
    ],
    digits: ["cbe", "gcbefd", "egdcba", "eafbdg"],
  },

  {
    signal: [
      "fecdb",
      "dgbcfae",
      "bedca",
      "edf",
      "ef",
      "cfebgd",
      "ecgf",
      "gfdbc",
      "fdbagc",
      "afbged",
    ],
    digits: ["aedbgf", "ef", "fecg", "fagcbd"],
  },

  {
    signal: [
      "gdecfb",
      "fbadge",
      "cabe",
      "adfcg",
      "efcbd",
      "ea",
      "gbeacfd",
      "fcedba",
      "dea",
      "fdeac",
    ],
    digits: ["acbe", "acbe", "dea", "fcgedba"],
  },

  {
    signal: [
      "bg",
      "dgfac",
      "gabdec",
      "dgcabef",
      "beafc",
      "gfceab",
      "cgb",
      "bafcde",
      "fegb",
      "cgafb",
    ],
    digits: ["bcg", "bg", "fdgca", "faebcg"],
  },

  {
    signal: [
      "adfgc",
      "dfcbge",
      "dgafbc",
      "gaf",
      "acfb",
      "dgcea",
      "gebcdaf",
      "fbgdea",
      "fbgdc",
      "af",
    ],
    digits: ["fa", "agcdf", "fga", "gfebda"],
  },

  {
    signal: [
      "defag",
      "begdf",
      "fa",
      "becgda",
      "aef",
      "afcg",
      "dfaceg",
      "cgdae",
      "eacdfb",
      "acefbgd",
    ],
    digits: ["cadfeb", "edgaf", "fa", "ecadbf"],
  },

  {
    signal: [
      "fec",
      "edfbc",
      "fagecd",
      "cgdfb",
      "ef",
      "fcabdg",
      "cedba",
      "fbecdg",
      "bfge",
      "faegbcd",
    ],
    digits: ["befdc", "dbfecga", "acgdbf", "gcbedfa"],
  },

  {
    signal: [
      "ed",
      "cedbfg",
      "bdfac",
      "fdeac",
      "baed",
      "fde",
      "eagcbdf",
      "abgfdc",
      "feadbc",
      "gaefc",
    ],
    digits: ["fdbca", "de", "cgbdfe", "de"],
  },

  {
    signal: [
      "fcbga",
      "ge",
      "cagbef",
      "acebfdg",
      "egbf",
      "acbge",
      "ceg",
      "egcdfa",
      "bagdcf",
      "adcbe",
    ],
    digits: ["cgfab", "ecg", "ebcda", "afgcde"],
  },

  {
    signal: [
      "df",
      "fadcbeg",
      "gcfbde",
      "dcagb",
      "fbd",
      "afgdbc",
      "cbeagd",
      "dfcab",
      "cafbe",
      "adfg",
    ],
    digits: ["eagdbcf", "fgda", "cgbda", "gbfced"],
  },

  {
    signal: [
      "agef",
      "bgdcaef",
      "ade",
      "adcbf",
      "gdbace",
      "cefdg",
      "febgdc",
      "cgefda",
      "fedca",
      "ae",
    ],
    digits: ["ae", "afdgec", "febgcd", "agcdeb"],
  },

  {
    signal: [
      "gfbc",
      "fdg",
      "dbaef",
      "fg",
      "aefgdcb",
      "gefdac",
      "gebcd",
      "dbegac",
      "fegcbd",
      "fbedg",
    ],
    digits: ["cfgb", "gdebc", "cbaefdg", "fgd"],
  },

  {
    signal: [
      "ebfgac",
      "gcf",
      "geabdfc",
      "cegbda",
      "fgade",
      "bcaeg",
      "fcba",
      "cf",
      "fdecgb",
      "ecafg",
    ],
    digits: ["cfg", "fgc", "acfgdeb", "gdabfec"],
  },

  {
    signal: [
      "gafeb",
      "ebdgac",
      "ed",
      "cgbfad",
      "cgeadfb",
      "bdecfa",
      "bfcda",
      "fabde",
      "aed",
      "ecdf",
    ],
    digits: ["bgfdaec", "fedcbag", "de", "fedc"],
  },

  {
    signal: [
      "age",
      "ebcdfg",
      "afcdeg",
      "dcfeg",
      "efadgbc",
      "fgad",
      "becad",
      "ag",
      "eacgd",
      "gabecf",
    ],
    digits: ["ag", "gcdfbe", "agecd", "fdgce"],
  },

  {
    signal: [
      "aecfbd",
      "geb",
      "afbde",
      "fdgeab",
      "gfeba",
      "ebgcadf",
      "bg",
      "gdbf",
      "fgeac",
      "bceagd",
    ],
    digits: ["eacdgfb", "bge", "edabcf", "ebdaf"],
  },

  {
    signal: [
      "cgabe",
      "aefbcdg",
      "fagdce",
      "abcdfg",
      "dcbe",
      "aecgbd",
      "cge",
      "fbaeg",
      "ce",
      "dcbga",
    ],
    digits: ["bgacfed", "gafcdb", "egc", "egc"],
  },

  {
    signal: [
      "bdefa",
      "fagbd",
      "fabdce",
      "cdae",
      "fceagb",
      "deb",
      "fbdecg",
      "fcbea",
      "de",
      "agedbcf",
    ],
    digits: ["fgdcabe", "afbde", "bde", "gfcbde"],
  },

  {
    signal: [
      "dgfcea",
      "dcbea",
      "dabcf",
      "edcbga",
      "cedafb",
      "gfabc",
      "cgdabfe",
      "afd",
      "fd",
      "dbfe",
    ],
    digits: ["debf", "egdacb", "dbef", "edabcg"],
  },

  {
    signal: [
      "bfdea",
      "adfceb",
      "fgcbae",
      "feg",
      "fdebg",
      "bagfdce",
      "egcdb",
      "fedagb",
      "dgaf",
      "gf",
    ],
    digits: ["bgdfea", "gef", "cdebfag", "edcbgaf"],
  },

  {
    signal: [
      "ade",
      "aefgdc",
      "ea",
      "feac",
      "gefdc",
      "eacbdfg",
      "eabfgd",
      "abcdg",
      "efbdgc",
      "geacd",
    ],
    digits: ["eafgdc", "fgebad", "cbdefg", "cdefg"],
  },

  {
    signal: [
      "egfdab",
      "edfb",
      "agfec",
      "dbcage",
      "ade",
      "ed",
      "badcfg",
      "gfcdeba",
      "afedg",
      "fgadb",
    ],
    digits: ["aedbcg", "bgfda", "aed", "dae"],
  },

  {
    signal: [
      "cfdbge",
      "abgc",
      "afgbe",
      "cb",
      "bcf",
      "ebfdga",
      "adecf",
      "efbacdg",
      "agfbce",
      "bacfe",
    ],
    digits: ["bfc", "fbc", "cfb", "bfc"],
  },

  {
    signal: [
      "gd",
      "bgd",
      "gcafeb",
      "dfcbage",
      "ebfgcd",
      "egfbd",
      "decg",
      "gcafdb",
      "aedfb",
      "ebgfc",
    ],
    digits: ["gdec", "gefbacd", "gdce", "dg"],
  },

  {
    signal: [
      "gf",
      "dbegac",
      "becgadf",
      "dfge",
      "facbe",
      "gfa",
      "acdgfe",
      "ecgfa",
      "dcfbag",
      "gceda",
    ],
    digits: ["gfed", "cefba", "cabfe", "acedfg"],
  },

  {
    signal: [
      "fd",
      "cdbagef",
      "fdgbec",
      "daebcg",
      "dfba",
      "fbacdg",
      "cdf",
      "cfadg",
      "gabdc",
      "gfcae",
    ],
    digits: ["agecf", "cfd", "cdf", "egcbad"],
  },

  {
    signal: [
      "dfca",
      "adgefb",
      "fbced",
      "cfdbge",
      "fa",
      "egcabfd",
      "eabcf",
      "eabfcd",
      "cabeg",
      "afe",
    ],
    digits: ["acfd", "dbecf", "af", "af"],
  },

  {
    signal: [
      "agfdec",
      "dfcag",
      "edgacfb",
      "baegfd",
      "fd",
      "gfaecb",
      "dacgb",
      "ecfga",
      "dfec",
      "daf",
    ],
    digits: ["gabcd", "ebcgadf", "fbegac", "fgace"],
  },

  {
    signal: [
      "edafg",
      "gcfea",
      "cbaeg",
      "afcdgbe",
      "fcde",
      "fc",
      "acf",
      "cedagf",
      "begfda",
      "cdbfag",
    ],
    digits: ["cf", "daecbfg", "bgace", "dcgabef"],
  },

  {
    signal: [
      "bdefagc",
      "gcba",
      "bfacde",
      "adbce",
      "ga",
      "dgefc",
      "cagdeb",
      "dgeabf",
      "aegdc",
      "adg",
    ],
    digits: ["faecdgb", "gda", "ag", "dga"],
  },

  {
    signal: [
      "becdag",
      "bceadf",
      "edcab",
      "dgacb",
      "bdgcaef",
      "gd",
      "dga",
      "cedg",
      "agbfc",
      "dafebg",
    ],
    digits: ["gd", "gced", "gad", "cgabd"],
  },

  {
    signal: [
      "gbfaed",
      "bdacf",
      "db",
      "fcabg",
      "ecfda",
      "edcb",
      "adcfge",
      "adb",
      "abcfed",
      "cgedfba",
    ],
    digits: ["bad", "dba", "fdecgab", "edacf"],
  },

  {
    signal: [
      "ae",
      "cabe",
      "ecgafb",
      "dfgce",
      "afbdge",
      "gdacfb",
      "bdegfca",
      "afe",
      "agfcb",
      "cegfa",
    ],
    digits: ["ae", "fgdeab", "gcfed", "cgdfabe"],
  },

  {
    signal: [
      "ad",
      "fdbcg",
      "cbfea",
      "fdabgec",
      "dca",
      "cgadfe",
      "fbdac",
      "dbag",
      "gbcfde",
      "bgcfad",
    ],
    digits: ["dbagfc", "dac", "ad", "cbfdge"],
  },

  {
    signal: [
      "fdgbaec",
      "ab",
      "dabe",
      "cabegd",
      "cgaed",
      "bcdag",
      "bgfdc",
      "gebcfa",
      "agb",
      "cadefg",
    ],
    digits: ["efbgac", "dcgafe", "dagecb", "gba"],
  },

  {
    signal: [
      "cafbge",
      "gdbfac",
      "aefcb",
      "adfcegb",
      "daefc",
      "bacge",
      "gcabed",
      "febg",
      "fb",
      "bfc",
    ],
    digits: ["bfcgae", "gebf", "bfc", "abgcdf"],
  },

  {
    signal: [
      "dfbgca",
      "bfcae",
      "ebc",
      "ebfdac",
      "eb",
      "eadfgcb",
      "dfeb",
      "edbagc",
      "fdcba",
      "gfcea",
    ],
    digits: ["becadf", "ecb", "bce", "badcf"],
  },

  {
    signal: [
      "cdefa",
      "adcgfe",
      "fdceb",
      "eacdfbg",
      "adf",
      "ad",
      "fcgea",
      "deag",
      "gacbfd",
      "aecfgb",
    ],
    digits: ["da", "dega", "adcebfg", "acdbefg"],
  },

  {
    signal: [
      "dace",
      "dcebg",
      "adbcfg",
      "abdcg",
      "de",
      "dceagb",
      "fcbeg",
      "fbacedg",
      "bdeafg",
      "deb",
    ],
    digits: ["bed", "cabgd", "ed", "fecbg"],
  },

  {
    signal: [
      "edabgc",
      "fdbaegc",
      "gcadfe",
      "afed",
      "fcd",
      "gecbf",
      "fd",
      "fgdcab",
      "fedcg",
      "dgace",
    ],
    digits: ["gaecd", "bdgcaf", "gedfcab", "fead"],
  },

  {
    signal: [
      "gfbae",
      "bgefdc",
      "cbfgdae",
      "dbgfea",
      "abgc",
      "bc",
      "aecbgf",
      "adfce",
      "bce",
      "afbce",
    ],
    digits: ["aedgfbc", "bacgfe", "bcdefg", "gfbea"],
  },

  {
    signal: [
      "cadeg",
      "cagdfb",
      "bdc",
      "bfcedga",
      "cgbafe",
      "facbe",
      "efbd",
      "edcba",
      "bafdec",
      "bd",
    ],
    digits: ["dbc", "agdce", "efdacb", "bcd"],
  },

  {
    signal: [
      "ac",
      "fegacb",
      "bac",
      "afdc",
      "aedfbc",
      "defba",
      "dgefba",
      "gcdeb",
      "edacb",
      "dcbeagf",
    ],
    digits: ["egdbc", "egcfbad", "decba", "adfc"],
  },

  {
    signal: [
      "bcfdag",
      "cgfdbea",
      "dce",
      "gbcfd",
      "ed",
      "bgced",
      "dfbgec",
      "gcaeb",
      "fcbead",
      "dgfe",
    ],
    digits: ["defg", "edc", "gecdb", "de"],
  },

  {
    signal: [
      "eb",
      "fbe",
      "afdec",
      "bfgda",
      "cdfbgae",
      "fbgcde",
      "aedbfc",
      "deafgc",
      "ecab",
      "efdba",
    ],
    digits: ["aegcdf", "fedgcab", "edcfbag", "be"],
  },

  {
    signal: [
      "cfabg",
      "aceg",
      "gba",
      "fcebda",
      "egabfc",
      "cbaef",
      "acfbdeg",
      "ga",
      "gcfdb",
      "adbfge",
    ],
    digits: ["cgae", "abg", "gace", "dfabec"],
  },

  {
    signal: [
      "fabe",
      "af",
      "fdaeg",
      "bdega",
      "fdceg",
      "adbfge",
      "fad",
      "gcedbfa",
      "dfgbac",
      "aedgbc",
    ],
    digits: ["afdgceb", "aebf", "dfa", "cgbaed"],
  },

  {
    signal: [
      "ecgdf",
      "bfcagd",
      "dcegb",
      "gafdc",
      "efac",
      "feadbgc",
      "agcdef",
      "eagbfd",
      "fge",
      "ef",
    ],
    digits: ["ef", "egf", "dcgfa", "decgf"],
  },

  {
    signal: [
      "ag",
      "ecbga",
      "bga",
      "fdegab",
      "gbdcfe",
      "gbecf",
      "afbecg",
      "ebdac",
      "edacgfb",
      "cagf",
    ],
    digits: ["gafc", "ecgbf", "bag", "eadgbf"],
  },

  {
    signal: [
      "dafe",
      "fe",
      "cef",
      "agdebfc",
      "fecdg",
      "bedcg",
      "bdcafg",
      "beafcg",
      "dcegaf",
      "fdcag",
    ],
    digits: ["dafe", "fcdag", "afdgce", "adef"],
  },

  {
    signal: [
      "gefac",
      "dagcfe",
      "age",
      "facdegb",
      "acfbg",
      "edfa",
      "ea",
      "edfcg",
      "egdcab",
      "fcbgde",
    ],
    digits: ["gcefa", "ea", "aebdgc", "ecfga"],
  },

  {
    signal: [
      "cdfbea",
      "debgca",
      "adbec",
      "bgfadc",
      "cdg",
      "ceadg",
      "bgce",
      "gc",
      "gfaed",
      "fcdgeab",
    ],
    digits: ["cg", "cgd", "afdcbg", "cdg"],
  },

  {
    signal: [
      "gcbefda",
      "fdcga",
      "cfdebg",
      "fgdabc",
      "abgd",
      "fdbcg",
      "cabfde",
      "fda",
      "efagc",
      "ad",
    ],
    digits: ["dgcfa", "bacfed", "cfbegd", "da"],
  },

  {
    signal: [
      "cgbaed",
      "bcdefg",
      "ebdca",
      "dcabf",
      "feabcdg",
      "cgae",
      "deabg",
      "ced",
      "ec",
      "efgdba",
    ],
    digits: ["bgdfce", "ceag", "cde", "dbegac"],
  },

  {
    signal: [
      "debgfa",
      "gbdce",
      "ecdgbf",
      "ag",
      "agdc",
      "bga",
      "acdgbfe",
      "bceag",
      "cbaef",
      "cebagd",
    ],
    digits: ["bga", "ga", "gaceb", "abecgd"],
  },

  {
    signal: [
      "dbgcef",
      "eafgb",
      "fcdeb",
      "bdfcae",
      "fadc",
      "ac",
      "degabc",
      "agbcefd",
      "abfce",
      "cba",
    ],
    digits: ["fcedb", "cebdga", "dacf", "dafcbeg"],
  },

  {
    signal: [
      "bag",
      "gceb",
      "cbafd",
      "bg",
      "bgfaec",
      "dfgcae",
      "cbagf",
      "gceaf",
      "dfageb",
      "bcafegd",
    ],
    digits: ["agb", "gb", "gb", "fedbagc"],
  },

  {
    signal: [
      "gadce",
      "gecdf",
      "cgf",
      "egbfd",
      "beagfc",
      "afdc",
      "dfcageb",
      "cf",
      "bcgdae",
      "dgefca",
    ],
    digits: ["fc", "gfc", "eacfdg", "cgf"],
  },

  {
    signal: [
      "dabcfg",
      "ebadf",
      "cf",
      "cebag",
      "fbc",
      "eagfcb",
      "bcegad",
      "fgce",
      "eabcf",
      "ebcgdaf",
    ],
    digits: ["feacbdg", "ebadf", "adfbe", "fc"],
  },

  {
    signal: [
      "ad",
      "fgeac",
      "afd",
      "bfagcde",
      "afbcde",
      "gdca",
      "debgf",
      "adgfe",
      "fbagec",
      "cfaged",
    ],
    digits: ["adcg", "adgefc", "ad", "adgcef"],
  },

  {
    signal: [
      "fcdbeag",
      "fdbage",
      "cadf",
      "daecb",
      "bgecd",
      "bafce",
      "bda",
      "ad",
      "cdbaef",
      "eacbgf",
    ],
    digits: ["ad", "caebdf", "gbcefa", "bcade"],
  },

  {
    signal: [
      "efbgca",
      "cabdgef",
      "fabcd",
      "dafec",
      "bf",
      "afdgcb",
      "fab",
      "agcbd",
      "fgbd",
      "dgceab",
    ],
    digits: ["fba", "fb", "dcagb", "dbfcag"],
  },

  {
    signal: [
      "bea",
      "cbfag",
      "agefdc",
      "cdeb",
      "gbadcef",
      "aefgdb",
      "eagdc",
      "cgdeba",
      "egbac",
      "be",
    ],
    digits: ["bgace", "eb", "be", "cbde"],
  },

  {
    signal: [
      "acbdeg",
      "cefda",
      "fb",
      "cfbaeg",
      "ebf",
      "aefcb",
      "gbfc",
      "ceagb",
      "cegbfda",
      "gebafd",
    ],
    digits: ["agcfbe", "afdec", "fbgc", "dfcegab"],
  },

  {
    signal: [
      "bc",
      "cgdab",
      "gbfcad",
      "ecbdfa",
      "cbd",
      "fgdac",
      "edfacgb",
      "dgaeb",
      "afecdg",
      "bcgf",
    ],
    digits: ["fcbg", "dbc", "dcafgb", "bcgf"],
  },

  {
    signal: [
      "aedf",
      "dga",
      "cgfbde",
      "fgbde",
      "cfbgad",
      "dabegf",
      "cfgabde",
      "geacb",
      "bdaeg",
      "da",
    ],
    digits: ["dfea", "agd", "baecg", "gcaeb"],
  },

  {
    signal: [
      "gc",
      "cefga",
      "dbefac",
      "bacedg",
      "afedg",
      "afcbe",
      "becgaf",
      "bcgf",
      "bdgfeac",
      "cag",
    ],
    digits: ["cgbf", "bgcf", "dabceg", "gc"],
  },

  {
    signal: [
      "db",
      "cdegf",
      "gcbfd",
      "afgbc",
      "dgcfba",
      "cbgaef",
      "dgba",
      "fgebacd",
      "fadcbe",
      "fdb",
    ],
    digits: ["fgebac", "bd", "fdegc", "db"],
  },

  {
    signal: [
      "debgafc",
      "dacbeg",
      "fdg",
      "cgdba",
      "fdagcb",
      "eacfg",
      "bdcf",
      "gafbde",
      "fd",
      "dcagf",
    ],
    digits: ["fbcd", "bgcefda", "cafbged", "dfbc"],
  },

  {
    signal: [
      "fcab",
      "gdbef",
      "begadc",
      "fdecga",
      "abdcefg",
      "bafgec",
      "cb",
      "cbe",
      "efbgc",
      "egacf",
    ],
    digits: ["bce", "gcfeb", "cgbfade", "cbaf"],
  },

  {
    signal: [
      "aedg",
      "agfebcd",
      "abfge",
      "fge",
      "cdbefg",
      "eg",
      "dgcfba",
      "gdebfa",
      "acbef",
      "gafbd",
    ],
    digits: ["agdfbc", "baefc", "efg", "gbfea"],
  },

  {
    signal: [
      "cdgab",
      "cbfedga",
      "eacbgd",
      "cf",
      "dceafg",
      "cadgfb",
      "fdc",
      "efbdg",
      "bcfa",
      "fdbgc",
    ],
    digits: ["dfc", "fc", "cdgbf", "gcbadf"],
  },

  {
    signal: [
      "gce",
      "eg",
      "edcfagb",
      "eacgdb",
      "bfegdc",
      "cdgaf",
      "ecgad",
      "cebadf",
      "eagb",
      "cedab",
    ],
    digits: ["dcbae", "cdafg", "gedacfb", "ge"],
  },

  {
    signal: [
      "dbeagf",
      "gfbda",
      "fdebgc",
      "gabfdc",
      "afbgc",
      "cgbea",
      "fc",
      "cdaf",
      "ecadbgf",
      "fcb",
    ],
    digits: ["cfgedb", "bdagf", "fc", "gbecfd"],
  },

  {
    signal: [
      "bdcefg",
      "egcfab",
      "acedg",
      "fcdb",
      "fbgeda",
      "bec",
      "cebdg",
      "deacbgf",
      "cb",
      "ebdfg",
    ],
    digits: ["bc", "decbg", "eacgd", "bdcf"],
  },

  {
    signal: [
      "dfgeab",
      "cegba",
      "facbegd",
      "edg",
      "dfgceb",
      "gafcbd",
      "edbgc",
      "gfcbd",
      "dcfe",
      "de",
    ],
    digits: ["bdceg", "fecd", "cedf", "defgcb"],
  },

  {
    signal: [
      "egfb",
      "dfgace",
      "cfgaebd",
      "befac",
      "adcgb",
      "aeg",
      "ge",
      "cebag",
      "bgface",
      "bdacfe",
    ],
    digits: ["cgbea", "cgbae", "cbdgaef", "afebgc"],
  },

  {
    signal: [
      "de",
      "efd",
      "efdbg",
      "efabdcg",
      "fgaceb",
      "bfgdc",
      "fgabe",
      "edgfab",
      "ebda",
      "degacf",
    ],
    digits: ["fecagd", "ed", "adbe", "de"],
  },

  {
    signal: [
      "fedbga",
      "gc",
      "gec",
      "gaefd",
      "ecagf",
      "gecbda",
      "bafce",
      "cgfead",
      "cgdf",
      "cadfbeg",
    ],
    digits: ["gafed", "gcfd", "cgfd", "gcfd"],
  },

  {
    signal: [
      "bedfgca",
      "ebfdc",
      "acgbfd",
      "cfb",
      "dfbeg",
      "decaf",
      "bc",
      "dabefc",
      "beac",
      "aedcgf",
    ],
    digits: ["debgf", "efacd", "cb", "bc"],
  },

  {
    signal: [
      "edgcba",
      "eg",
      "dbfga",
      "acfgeb",
      "cdbea",
      "bcfdaeg",
      "dcge",
      "gdeba",
      "dacefb",
      "egb",
    ],
    digits: ["efgdacb", "cgeafbd", "gfadb", "gedc"],
  },

  {
    signal: [
      "bacfde",
      "dgcefa",
      "eabdf",
      "acfebdg",
      "afgdbc",
      "dba",
      "aedfc",
      "aebgf",
      "db",
      "bdce",
    ],
    digits: ["db", "afecd", "agcdfe", "agfedbc"],
  },

  {
    signal: [
      "dga",
      "cgadb",
      "cdbge",
      "bfgca",
      "edab",
      "ad",
      "cbgade",
      "efbcdga",
      "afedgc",
      "ecfgbd",
    ],
    digits: ["ad", "dgecb", "ad", "bdgac"],
  },

  {
    signal: [
      "abfdec",
      "dacfegb",
      "faecg",
      "cbge",
      "acgfb",
      "fcgaeb",
      "bgfda",
      "bc",
      "bfc",
      "fgcdae",
    ],
    digits: ["cgeb", "fgaecb", "cbeg", "gadbefc"],
  },

  {
    signal: [
      "ea",
      "ecgbfda",
      "eacb",
      "efa",
      "facegb",
      "bgfea",
      "ebfdg",
      "gfbac",
      "edcgaf",
      "gcdfba",
    ],
    digits: ["gabfe", "bgfeca", "ae", "cabe"],
  },

  {
    signal: [
      "ecf",
      "bfged",
      "cebfgd",
      "adfebg",
      "dfabec",
      "cgdf",
      "gbeca",
      "cf",
      "bdfcgea",
      "bgfce",
    ],
    digits: ["cdfgeab", "gdbfe", "daebcf", "bcagdef"],
  },

  {
    signal: [
      "ebf",
      "efbdc",
      "bf",
      "bfcdge",
      "dgcfea",
      "bgfc",
      "cedab",
      "begdaf",
      "egcdf",
      "befdcag",
    ],
    digits: ["ebgcfda", "gdfaeb", "bf", "ecfgd"],
  },

  {
    signal: [
      "egcdf",
      "ecafg",
      "afebdc",
      "df",
      "dgfa",
      "agfecd",
      "cfbdgea",
      "ecgafb",
      "gdceb",
      "cfd",
    ],
    digits: ["cdf", "cgadef", "acfgbde", "defgc"],
  },

  {
    signal: [
      "gbdeacf",
      "bfcdg",
      "cag",
      "acdgf",
      "efdbcg",
      "ac",
      "fagdcb",
      "gbfeac",
      "bcda",
      "edfga",
    ],
    digits: ["agc", "gaedf", "abdc", "cag"],
  },

  {
    signal: [
      "cfgd",
      "edbcfg",
      "gfebc",
      "begcdfa",
      "acebgf",
      "ged",
      "dbace",
      "faedbg",
      "gecbd",
      "gd",
    ],
    digits: ["bagefc", "dgefabc", "defabg", "becgf"],
  },

  {
    signal: [
      "gcbe",
      "ce",
      "ebdfa",
      "cae",
      "bdcagfe",
      "bgdac",
      "gdeacb",
      "cbdagf",
      "dbace",
      "caegfd",
    ],
    digits: ["ec", "acedb", "gabcd", "bcagfed"],
  },

  {
    signal: [
      "efdgba",
      "cgabfed",
      "ec",
      "caef",
      "ceagb",
      "fbega",
      "cbgda",
      "ebc",
      "afbgec",
      "ecbdgf",
    ],
    digits: ["afegdb", "gacbd", "dgefab", "edafgb"],
  },

  {
    signal: [
      "ecagd",
      "bfdec",
      "fabdce",
      "bda",
      "beadc",
      "gfeabd",
      "bdfeacg",
      "afbc",
      "gecbfd",
      "ba",
    ],
    digits: ["becdf", "dcaeg", "gcdea", "adb"],
  },

  {
    signal: [
      "cefb",
      "cfabdg",
      "dbf",
      "bfeacd",
      "baged",
      "bf",
      "baefd",
      "gaecfd",
      "cbfaedg",
      "fecda",
    ],
    digits: ["bf", "fedac", "fdgecba", "bdf"],
  },

  {
    signal: [
      "gce",
      "gdbcae",
      "fecd",
      "efcbgd",
      "fbdacg",
      "eafbg",
      "cefgb",
      "cbdfg",
      "ec",
      "fgdacbe",
    ],
    digits: ["cge", "ec", "bgcfead", "ceg"],
  },

  {
    signal: [
      "deagfb",
      "af",
      "efca",
      "gfecad",
      "dfa",
      "bacdg",
      "cfdegb",
      "fecdg",
      "egdacfb",
      "dfcag",
    ],
    digits: ["fdgce", "af", "edbgafc", "fdgce"],
  },

  {
    signal: [
      "fagdce",
      "ebd",
      "abdegf",
      "defba",
      "cafebdg",
      "eb",
      "daefg",
      "dfbca",
      "ebga",
      "defcbg",
    ],
    digits: ["afdeb", "eb", "bde", "egba"],
  },

  {
    signal: [
      "bafed",
      "aecdb",
      "fbce",
      "cbd",
      "gdebafc",
      "cfbadg",
      "badegf",
      "bc",
      "ecdfab",
      "gecad",
    ],
    digits: ["dbc", "dbc", "badgcfe", "fdgeba"],
  },

  {
    signal: [
      "fgbec",
      "bfacde",
      "ge",
      "edgcfb",
      "cgdbfae",
      "fdecga",
      "cfbga",
      "efg",
      "dbge",
      "cdfeb",
    ],
    digits: ["bedfcg", "eg", "ge", "afebdcg"],
  },

  {
    signal: [
      "dcaef",
      "ag",
      "gcab",
      "aeg",
      "acedg",
      "edgcb",
      "efgdacb",
      "cgfbed",
      "dafgeb",
      "agdbec",
    ],
    digits: ["bedagc", "bdegc", "dfcebg", "adecf"],
  },

  {
    signal: [
      "dcfg",
      "abecg",
      "bgadc",
      "dg",
      "fcgbda",
      "gadebf",
      "cdabfe",
      "badcf",
      "agd",
      "fcdbega",
    ],
    digits: ["abdfeg", "gd", "egbac", "cabgdf"],
  },

  {
    signal: [
      "dfgebc",
      "eabcd",
      "efcdb",
      "dbecfa",
      "dac",
      "aegdb",
      "ca",
      "bcgafed",
      "fbac",
      "fcadge",
    ],
    digits: ["ca", "egcdafb", "afcbdge", "eagdb"],
  },

  {
    signal: [
      "ebgdc",
      "cbgdfe",
      "dcbfae",
      "bfagcd",
      "gdef",
      "cebga",
      "bceagfd",
      "ecd",
      "dfbgc",
      "ed",
    ],
    digits: ["de", "ed", "fdegcba", "edc"],
  },

  {
    signal: [
      "eb",
      "feb",
      "begdcf",
      "efgacb",
      "gdbe",
      "daecf",
      "dgcfb",
      "fbdcega",
      "cebfd",
      "gabcdf",
    ],
    digits: ["efdbc", "be", "afdec", "efb"],
  },

  {
    signal: [
      "begac",
      "fbec",
      "bcdafg",
      "acb",
      "cb",
      "fgaebd",
      "afegbc",
      "gebadcf",
      "dagec",
      "beafg",
    ],
    digits: ["adgce", "fceb", "cgdeafb", "cab"],
  },

  {
    signal: [
      "ca",
      "cdfagb",
      "ebfca",
      "ebdcgaf",
      "afebg",
      "dfbgae",
      "cega",
      "cebfd",
      "fbagce",
      "fac",
    ],
    digits: ["bgedaf", "cgae", "gdaecfb", "egdabcf"],
  },

  {
    signal: [
      "gabfd",
      "agfc",
      "ecdbfag",
      "aefcbd",
      "afd",
      "af",
      "gdabfc",
      "bgcfed",
      "abedg",
      "dcgfb",
    ],
    digits: ["af", "bdgcef", "adgbf", "gcdafb"],
  },

  {
    signal: [
      "egfda",
      "fed",
      "dbfga",
      "adgefb",
      "de",
      "gacbdf",
      "aefgc",
      "aecbfd",
      "bdge",
      "fdbecga",
    ],
    digits: ["ed", "de", "eacbgdf", "bdeg"],
  },

  {
    signal: [
      "dbfag",
      "cdbfea",
      "gfdbec",
      "agfedbc",
      "gfb",
      "bg",
      "gabfcd",
      "fgeda",
      "dbfac",
      "acbg",
    ],
    digits: ["dfbac", "gcba", "gb", "fbgda"],
  },

  {
    signal: [
      "dbcgf",
      "gba",
      "gdcaeb",
      "dgbacfe",
      "edfba",
      "debgcf",
      "cbdgaf",
      "afcg",
      "ag",
      "abfdg",
    ],
    digits: ["bgafecd", "edfcgb", "ag", "dgfba"],
  },

  {
    signal: [
      "bdfcg",
      "acebfg",
      "egfbacd",
      "gfdcba",
      "fbg",
      "dagb",
      "bg",
      "cbdaf",
      "cgdfe",
      "edfcab",
    ],
    digits: ["bagd", "gfebacd", "efbcda", "gfb"],
  },

  {
    signal: [
      "cedbf",
      "fcabdge",
      "cge",
      "feagbc",
      "dfcge",
      "gedb",
      "adcgf",
      "bdcefg",
      "edacfb",
      "eg",
    ],
    digits: ["cbdfe", "cge", "efbcad", "cfagdeb"],
  },

  {
    signal: [
      "cga",
      "fgeda",
      "ceagd",
      "ebcg",
      "beadc",
      "bgfecad",
      "fgdcba",
      "gc",
      "cagebd",
      "dfeabc",
    ],
    digits: ["cag", "daebgc", "cg", "fcdageb"],
  },

  {
    signal: [
      "fgdc",
      "fda",
      "aebgd",
      "cabfde",
      "fd",
      "agbecf",
      "fdacgbe",
      "dbfga",
      "cfgba",
      "bdgacf",
    ],
    digits: ["facbg", "fbdagec", "fdcg", "ebafcgd"],
  },

  {
    signal: [
      "gbced",
      "efbgca",
      "gfebd",
      "bdc",
      "baecg",
      "fcabed",
      "dcbgeaf",
      "gbedac",
      "dc",
      "acdg",
    ],
    digits: ["gfbace", "cdafbe", "cbaeg", "bcd"],
  },

  {
    signal: [
      "afgdec",
      "ba",
      "dbcge",
      "daefg",
      "dabeg",
      "dfbcage",
      "afbd",
      "fgdaeb",
      "gab",
      "cfegab",
    ],
    digits: ["bcfage", "bgead", "ba", "fgdbcea"],
  },

  {
    signal: [
      "ace",
      "dgcaef",
      "daegbc",
      "bfgeda",
      "ecbd",
      "degab",
      "cgabf",
      "ce",
      "eagbdfc",
      "bcgea",
    ],
    digits: ["cdgeaf", "bdgea", "edcb", "cae"],
  },

  {
    signal: [
      "cd",
      "cadf",
      "gfead",
      "gdefab",
      "dce",
      "adcfge",
      "degcf",
      "cgefb",
      "gdfbcae",
      "aebcgd",
    ],
    digits: ["efgdc", "dce", "ecd", "dc"],
  },

  {
    signal: [
      "afdbe",
      "ad",
      "fgdeb",
      "fda",
      "aebdcgf",
      "bcaefg",
      "acbfe",
      "fdceab",
      "bacd",
      "dcagef",
    ],
    digits: ["afd", "begfd", "acfeb", "fda"],
  },

  {
    signal: [
      "dfg",
      "afgedbc",
      "cbfga",
      "gbdace",
      "dbagf",
      "fdegab",
      "edgacf",
      "df",
      "befd",
      "edgba",
    ],
    digits: ["dgeba", "df", "efbd", "cfadge"],
  },

  {
    signal: [
      "bdcgaf",
      "aebg",
      "badfce",
      "efagc",
      "gdefc",
      "cabfeg",
      "abgcf",
      "ecafbdg",
      "afe",
      "ae",
    ],
    digits: ["aegdbcf", "ageb", "eagb", "ebdfgca"],
  },

  {
    signal: [
      "gdceab",
      "fb",
      "bfe",
      "cgbfea",
      "edbagfc",
      "cafed",
      "ebacg",
      "ebafc",
      "defgcb",
      "gbfa",
    ],
    digits: ["efb", "efcba", "bf", "afgb"],
  },

  {
    signal: [
      "bafcg",
      "cdfgb",
      "ac",
      "caf",
      "fcdabe",
      "adgc",
      "dbgefc",
      "bedafcg",
      "bgacdf",
      "bfaeg",
    ],
    digits: ["bcfegad", "afegb", "gabfdce", "bgcfa"],
  },

  {
    signal: [
      "dafgb",
      "gca",
      "fcab",
      "fcabgd",
      "dcfaebg",
      "gfcdae",
      "cgdba",
      "ac",
      "gbadef",
      "egcbd",
    ],
    digits: ["bcedg", "aebgfcd", "gfeadb", "afbc"],
  },

  {
    signal: [
      "adebg",
      "fcgaedb",
      "dagfe",
      "agfc",
      "fdbaec",
      "fgaecd",
      "feg",
      "acdfe",
      "gf",
      "becdgf",
    ],
    digits: ["feg", "fge", "gfe", "egf"],
  },

  {
    signal: [
      "gf",
      "gfda",
      "gfb",
      "gfcebd",
      "gefab",
      "afcbged",
      "eabdg",
      "adgbfe",
      "fbace",
      "bgcade",
    ],
    digits: ["dbafgce", "fbdaeg", "dagf", "fcbae"],
  },

  {
    signal: [
      "fbegcd",
      "ecg",
      "cefdbag",
      "fcgd",
      "ebdac",
      "gbecd",
      "cg",
      "bfcgea",
      "bafdeg",
      "edfgb",
    ],
    digits: ["fcbegd", "acbde", "bcgaef", "cge"],
  },

  {
    signal: [
      "gbcadf",
      "cf",
      "gfbc",
      "defbca",
      "acgfd",
      "bcaedg",
      "afegd",
      "cfbgeda",
      "caf",
      "gcdba",
    ],
    digits: ["begcad", "cfa", "bagfedc", "gbcdeaf"],
  },

  {
    signal: [
      "begacdf",
      "dcafbg",
      "gb",
      "cgfbed",
      "gbcde",
      "cedfab",
      "dfcbe",
      "gbc",
      "cadge",
      "ebfg",
    ],
    digits: ["gbfe", "gb", "ebcdfga", "bfeg"],
  },

  {
    signal: [
      "fe",
      "bgadefc",
      "cbgdf",
      "gbfade",
      "cefgd",
      "ecdgaf",
      "efg",
      "afce",
      "eacgd",
      "dcgeab",
    ],
    digits: ["gdebac", "fcae", "egbdfac", "fgdeab"],
  },

  {
    signal: [
      "ebfca",
      "fdac",
      "fdb",
      "bgdecaf",
      "dbcgef",
      "cedbfa",
      "bgcefa",
      "fd",
      "eadfb",
      "baegd",
    ],
    digits: ["cgfaeb", "dgbecf", "dfb", "bagecf"],
  },

  {
    signal: [
      "ebda",
      "eagcf",
      "gcbea",
      "ba",
      "bfcegad",
      "acebgd",
      "gdecb",
      "cdafgb",
      "acb",
      "gfcdbe",
    ],
    digits: ["fgcebd", "cedbgf", "gbfdac", "cefag"],
  },

  {
    signal: [
      "edacf",
      "fed",
      "eacgd",
      "febadc",
      "ebafc",
      "bfcgea",
      "ecafgdb",
      "adbf",
      "fd",
      "gbfdec",
    ],
    digits: ["fabce", "egfcbd", "deafgbc", "bafd"],
  },

  {
    signal: [
      "gfbe",
      "fdbga",
      "ged",
      "ge",
      "aegdf",
      "baegcd",
      "afecd",
      "ebgcfda",
      "fgacbd",
      "gdeafb",
    ],
    digits: ["cdfae", "fdaec", "ge", "aefdg"],
  },

  {
    signal: [
      "gebaf",
      "afdbcg",
      "cfged",
      "dga",
      "fgead",
      "febdcga",
      "ad",
      "fbaedg",
      "bade",
      "gbfaec",
    ],
    digits: ["cgbfdea", "gadfecb", "agfde", "gad"],
  },

  {
    signal: [
      "fdg",
      "cfgdbe",
      "cfbeadg",
      "cgbf",
      "gedbc",
      "dcfage",
      "dfgeb",
      "fg",
      "agcbed",
      "adefb",
    ],
    digits: ["gdf", "bdecg", "faedb", "gfd"],
  },

  {
    signal: [
      "acdgbe",
      "cfabg",
      "gfbacd",
      "cbf",
      "dfbcea",
      "bcfegad",
      "cf",
      "gcdab",
      "efbag",
      "fdcg",
    ],
    digits: ["dbfagc", "fgbdcea", "cbdga", "fc"],
  },

  {
    signal: [
      "afbcg",
      "dgbfac",
      "dgaebf",
      "gcfea",
      "gbceadf",
      "afb",
      "fb",
      "abgcd",
      "abcdge",
      "fdcb",
    ],
    digits: ["gbceda", "cgdabe", "bcgdae", "fbgdea"],
  },

  {
    signal: [
      "cgbedf",
      "dbgfc",
      "cbef",
      "cf",
      "bgfda",
      "gcedb",
      "gadceb",
      "efdcag",
      "fdc",
      "bcfdaeg",
    ],
    digits: ["fecb", "ebdcfg", "cf", "badgf"],
  },

  {
    signal: [
      "fg",
      "cafdg",
      "fegadbc",
      "aefcdb",
      "bcagd",
      "degf",
      "gfecba",
      "adegfc",
      "cfg",
      "fdeac",
    ],
    digits: ["gdcafe", "cgfdae", "gebfca", "dfcgae"],
  },

  {
    signal: [
      "fdbecg",
      "fcagbd",
      "fgeabd",
      "cadbe",
      "bcdag",
      "dafgb",
      "facg",
      "gdc",
      "bdgeacf",
      "cg",
    ],
    digits: ["cedab", "cbdga", "gcd", "gc"],
  },

  {
    signal: [
      "gdeaf",
      "edbcag",
      "fbac",
      "fgecdba",
      "dfbcea",
      "afdce",
      "ac",
      "fbecd",
      "dbefcg",
      "cea",
    ],
    digits: ["efcbd", "gdeaf", "dfceagb", "ace"],
  },

  {
    signal: [
      "abgdc",
      "ebcgd",
      "ecgdf",
      "ebagcd",
      "dabe",
      "edgbcfa",
      "be",
      "cgeabf",
      "ceb",
      "cdfgba",
    ],
    digits: ["fdacbg", "abegcd", "abdgc", "cabfdge"],
  },

  {
    signal: [
      "fbgcd",
      "feacb",
      "ed",
      "eadf",
      "becfd",
      "bde",
      "fdabce",
      "cgdbea",
      "fadbcge",
      "gbefac",
    ],
    digits: ["dcgbf", "fcebd", "ebcfd", "gbface"],
  },
];
